codecov:
  branch: master
  token: secret:4ZHXRTlW9gZ538DdSjpIxGqe5PhzEbrR3GHuryXkr3yQ1txbm+kM9MhV1AhfYNbBBs+TOLkDyTgQl9sAHKHeRAmTaUaWbnkfx+9UK9sYf0Q=

coverage:
  range: 70...95
  round: nearest
  precision: 2
  notify:
    slack:
      default:
        url: https://hooks.slack.com/services/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
        threshold: 0%
        only_pulls: false
        branches: null
        flags: null
        paths: null
